version: "3"

services:
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  clickhouse-server:
    extends:
      file: docker-compose.base.yml
      service: clickhouse-server

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    depends_on:
      - postgres
      - clickhouse-server
      - redis
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
      CLICKHOUSE_URL: "clickhouse://default:@clickhouse-server:8123/default"
      REDIS_URL: "redis:6379"
      NODE_ENV: "development"

  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    restart: on-failure
    depends_on:
      - postgres
      - redis
      - clickhouse-server
      - consumer
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
      CLICKHOUSE_URL: "clickhouse://default:@clickhouse-server:8123/default"
      REDIS_URL: "redis:6379"
      NODE_ENV: "development"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:
