version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    shm_size: 4g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "18123:8123"
      - "19000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    depends_on:
      - postgres
      - clickhouse-server
      - redis
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"
      CLICKHOUSE_URL: "http://clickhouse-server:18123"
      REDIS_URL: "redis:6379"
      NODE_ENV: "development"

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:
