version: "3"

services:
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  clickhouse-server:
    extends:
      file: docker-compose.base.yml
      service: clickhouse-server

  consumer:
    extends:
      file: docker-compose.base.yml
      service: consumer

  webapp:
    build:
      context: dashboard/
    command: npm run start
    restart: on-failure
    depends_on:
      - db
      - redis
      - clickhouse-server
      - consumer

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:
